export const rewards = [
    {
        id: 1,
        title: "Fast Start Bonus",
        value: "₹1,000",
        description: "Awarded for reaching Ruby rank within your first 30 days.",
        status: "UNLOCKED",
        statusColor: "bg-green-100 text-green-700",
        bgColor: "bg-green-50",
        icon: "payments",
        iconColor: "text-green-600",
        claimedDate: "Claimed on Feb 12",
        showClaim: false,
    },
    {
        id: 2,
        title: "Elite Timepiece",
        value: "₹2,500 Val.",
        description:
            "Reached Platinum rank and maintained for 2 consecutive months.",
        status: "READY TO CLAIM",
        statusColor: "bg-blue-100 text-blue-700",
        bgColor: "bg-blue-50",
        icon: "schedule",
        iconColor: "text-blue-600",
        showClaim: true,
    },
    {
        id: 3,
        title: "Luxury Car Allowance",
        value: "₹15k Fund",
        description: "Maintain Diamond rank with 20,000 Group Volume.",
        status: "IN PROGRESS",
        statusColor: "bg-slate-100 text-slate-700",
        bgColor: "bg-slate-50",
        icon: "directions_car",
        iconColor: "text-slate-400",
        progress: 75,
        progressText: "75% COMPLETE",
    },
    {
        id: 4,
        title: "Annual Leadership Retreat",
        value: "Priceless",
        description:
            "Must reach Blue Diamond rank before the December 31st deadline.",
        status: "LOCKED",
        statusColor: "bg-slate-100 text-slate-500",
        bgColor: "bg-slate-100",
        icon: "flight",
        iconColor: "text-slate-300",
        lockText: "Next available at Blue Diamond",
    },
    {
        id: 5,
        title: "Profit Sharing Pool",
        value: "Variable",
        description:
            "Participate in 2% of the global company turnover quarterly.",
        status: "LOCKED",
        statusColor: "bg-slate-100 text-slate-500",
        bgColor: "bg-slate-100",
        icon: "account_balance",
        iconColor: "text-slate-300",
        lockText: "Next available at Ambassador",
    },
    {
        id: 6,
        title: "Founder's Equity Grant",
        value: "100k Units",
        description:
            "Legacy reward for consistent top-tier performance over 24 months.",
        status: "LOCKED",
        statusColor: "bg-slate-100 text-slate-500",
        bgColor: "bg-slate-100",
        icon: "handshake",
        iconColor: "text-slate-300",
        lockText: "Next available at Crown Ambassador",
    },
];

export const careerRoadmap = [
    {
        rank: "Ruby",
        status: "COMPLETED",
        color: "bg-primary",
        textColor: "text-primary",
    },
    {
        rank: "Platinum",
        status: "COMPLETED",
        color: "bg-primary",
        textColor: "text-primary",
    },
    {
        rank: "DIAMOND",
        status: "CURRENT",
        color: "bg-primary",
        textColor: "text-primary",
        current: true,
    },
    {
        rank: "Blue Diamond",
        status: "LOCKED",
        color: "bg-slate-300",
        textColor: "text-slate-400",
    },
    {
        rank: "Ambassador",
        status: "LOCKED",
        color: "bg-slate-300",
        textColor: "text-slate-400",
    },
];
